spring:
  cloud:
    gateway:
      routes:
      - id: httpbin
        uri: http://127.0.0.1
        predicates:
        - Path=/18f/api/**
        filters:
        - StripPrefix=2
        - VerifyJwt=Authorization
        - AddWcsTokensFromJwt=Authorization



