spring:
  cache:
    cache-names: wcsession-tokens
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=14400s

  cloud:
    gateway:
      routes:
      - id: httpbin
        uri: http://127.0.0.1
        predicates:
        - Path=/18f/api/**
        filters:
        - StripPrefix=2
        - VerifyJwt=Authorization
        - AddWcsTokensFromJwt=Authorization
