spring:
  cloud:
    gateway:
      routes:
      - id: httpbin
        uri: http://httpbin.org
        predicates:
        - Path=/r/httpbin/{segment}
        filters:
        - SetPath=/{segment}
        - AddRequestHeader=Foo, Bar
